app:
    resource: '@AppBundle/Controller/'
    type: annotation

create_currency:
    path: /create_currency
    defaults: { _controller: AppBundle:Default:createCurrency }

show_currency:
    path: /show_currency/{currencyId}
    defaults: { _controller: AppBundle:Default:showCurrency }