app:
    resource: '@AppBundle/Controller/'
    type: annotation

create_currency:
    path: /create_currency
    defaults: { _controller: AppBundle:Default:createCurrency }

show_currency:
    path: /show_currency/{currencyId}
    defaults: { _controller: AppBundle:Default:showCurrency }

update_currency:
    path: /update_currency/{currencyId}
    defaults: { _controller: AppBundle:Default:updateCurrency }

new:
    path: new
    defaults: { _controller: AppBundle:Default:new }

calculator:
    path: calculator
    defaults: { 
                _controller: AppBundle:Default:calculator
              }

calculate:
    path: calculate
    defaults: { 
                _controller: AppBundle:Default:calculate
              }